### ISSUE TITLE
Design Structure and Development

### ISSUE THREAD

**Issue by DevNathi** [izinkabi/HandymanWorkspace#18]
### OWNER ###
**Current Pages**
- Dashboard
- Services
- Orders
- Stuff
- Business
- Reports
- Revenue

**Details**
The UI has structure and styling to make it fit the designed provided. 

**Requirements**
 Dashboard:

- stats -
- control panel - 
- search , Filter, sorting - All in one search 
- Footer -

Services :
-list services and sort, filter and search services
- Add services using a pop up or modal
- manipulate the status, availability of a service and remove a service. Alos be able to assign service to a stuff, location, or address.
- -- Stats on the views on services and performance of the employee, service and location.
Orders:
-List incoming requests, negotiate the request and turn it into an order.
- process payment or deposits and display receipts 
- Prioritize orders based on date, time, location and availability of stuff and service
Revenues:
- get a total number of receipts for a certain period of time and sum them up.
- expenses e.g. service fee, stuff payments, workshop costs
Stuff:
- List available stuff, locations
- employe, promote or retrench stuff.
Workshop:
- Recruit members to join workshop
- Add locations, assign roles
- List services per location
- Assign stuff to location and services
Reporting:
- stats about stuff, workshop and location performance summary you can export to csv,pdf
- display analytics about the daily, weekly and monthly operation of the workshop, locations and employees. 
- compare declined and closed orders and estimate the revenue that could have been gained,
- report on receipts and refunds.

### TODO

- [ ] Conclude the creation of the side navigation pages, structure, style and animate the pages'
- [ ] Display user information, profile and account edit
- [ ] Complete the UI Template and apply on the API_Prototype branch
- [ ]
